apiVersion: v1
kind: ConfigMap
metadata:
  name: skeletons
  namespace: default
data:
  detector: |-
    {
      "broker_uri": "amqp://rabbitmq.default",
      "zipkin_host": "zipkin.default",
      "zipkin_port": 9411,
      "models_folder": "/",
      "resize": {
        "width": 720,
        "height": 544
      },
      "model": "MOBILENET_THIN",
      "resize_out_ratio": 4.0
    }
  grouper_1000: |-
    {
      "broker_uri": "amqp://rabbitmq.default",
      "zipkin_host": "zipkin.default",
      "zipkin_port": 9411,
      "cameras_ids": [0, 1, 2, 3, 4],
      "referencial": 1000,
      "min_error": 50.0,
      "period_ms": 100
    }
  heatmap_1000: |-
    {
      "broker_uri": "amqp://10.10.2.15:30000",
      "zipkin_host": "10.10.2.15",
      "zipkin_port": 30200,
      "topic_id": 1000,
      "limits": {
        "xmin": -2.5,
        "xmax": 5.0,
        "ymin": -2.5,
        "ymax": 5.0
      },
      "bins_step": 0.05,
      "output_scale": 5.0,
      "referencial": {
        "x": 0.0,
        "y": 0.0,
        "length": 50
      },
      "draw_grid": true,
      "flip_horizontal": true,
      "flip_vertical": false,
      "log_scale": true,
      "average_coordinates": false
    }

---

apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: "is-skeletons-detector"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: detector
    spec:
      containers:
      - name: "0"
        image: viros/is-skeletons:1.1-detector
        command: ["python"]
        args: ["stream.py", "/opt/options.json"]
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: "2"
            memory: 2048Mi
            nvidia.com/gpu: 1
        volumeMounts:
          - name: options
            mountPath: /opt
      - name: "1"
        image: viros/is-skeletons:1.1-detector
        command: ["python"]
        args: ["stream.py", "/opt/options.json"]
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: "2"
            memory: 2048Mi
        volumeMounts:
          - name: options
            mountPath: /opt
      - name: "2"
        image: viros/is-skeletons:1.1-detector
        command: ["python"]
        args: ["stream.py", "/opt/options.json"]
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: "2"
            memory: 2048Mi
        volumeMounts:
          - name: options
            mountPath: /opt
      - name: "3"
        image: viros/is-skeletons:1.1-detector
        command: ["python"]
        args: ["stream.py", "/opt/options.json"]
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: "2"
            memory: 2048Mi
        volumeMounts:
          - name: options
            mountPath: /opt
      volumes:
      - name: options
        configMap:
          name: skeletons
          items:
          - key: detector
            path: options.json

---

apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: "is-skeletons-grouper-1000"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grouper
    spec:
      containers:
      - name: "0"
        image: viros/is-skeletons-grouper:2.1
        command: ["/service.bin"]
        args: ["/opt/options.json"]
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: "1"
            memory: 128Mi
        volumeMounts:
          - name: options
            mountPath: /opt
      volumes:
      - name: options
        configMap:
          name: skeletons
          items:
          - key: grouper_1000
            path: options.json

---

apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: "is-skeletons-heatmap-1000"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: heatmap
    spec:
      containers:
      - name: "0"
        image: viros/is-skeletons-heatmap:1.1
        command: ["python"]
        args: ["service.py", "/opt/options.json"]
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: "1"
            memory: 256Mi
        volumeMounts:
          - name: options
            mountPath: /opt
      volumes:
      - name: options
        configMap:
          name: skeletons
          items:
          - key: heatmap_1000
            path: options.json
