apiVersion: v1
kind: ConfigMap
metadata:
  name: skeletons-grouper
  namespace: default
data:
  grouper_0: |-
    {
      "broker_uri": "amqp://rabbitmq.default",
      "zipkin_host": "zipkin.default",
      "zipkin_port": 9411,
      "cameras": {
        "0": { "max_width": { "value": 0.5 }},
        "1": {},
        "2": {},
        "3": {},
        "4": {}
      },
      "referential": 1000,
      "min_error": 30.0,
      "min_score": 0.4,
      "period_ms": 200,
      "release_samples": 5
    }
  grouper_1: |-
    {
      "broker_uri": "amqp://rabbitmq.default",
      "zipkin_host": "zipkin.default",
      "zipkin_port": 9411,
      "cameras": {
        "0": { "min_width": { "value": 0.5 }},
        "2": {},
        "4": {},
        "6": {}
      },
      "referential": 1001,
      "min_error": 30.0,
      "min_score": 0.4,
      "period_ms": 200,
      "release_samples": 5
    }
  grouper_2: |-
    {
      "broker_uri": "amqp://rabbitmq.default",
      "zipkin_host": "zipkin.default",
      "zipkin_port": 9411,
      "cameras_ids": [5, 6, 7],
      "cameras": {
        "5": {},
        "6": { "min_width": { "value": 0.25 }, "max_width": { "value": 0.75 }},
        "7": {}
      },
      "referential": 1003,
      "min_error": 30.0,
      "min_score": 0.4,
      "period_ms": 200,
      "release_samples": 5
    }

---

apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: "is-skeletons-grouper"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grouper
    spec:
      containers:
      - name: "0"
        image: viros/is-skeletons-grouper:2.7
        command: ["/service.bin"]
        args: ["/opt/options_0.json"]
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: "1"
            memory: 128Mi
        volumeMounts:
          - name: options
            mountPath: /opt
      - name: "1"
        image: viros/is-skeletons-grouper:2.7
        command: ["/service.bin"]
        args: ["/opt/options_1.json"]
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: "1"
            memory: 128Mi
        volumeMounts:
          - name: options
            mountPath: /opt
      - name: "2"
        image: viros/is-skeletons-grouper:2.7
        command: ["/service.bin"]
        args: ["/opt/options_2.json"]
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: "1"
            memory: 128Mi
        volumeMounts:
          - name: options
            mountPath: /opt
      volumes:
      - name: options
        configMap:
          name: skeletons-grouper
          items:
          - key: grouper_0
            path: options_0.json
          - key: grouper_1
            path: options_1.json
          - key: grouper_2
            path: options_2.json
