apiVersion: v1
kind: ConfigMap
metadata:
  name: skeletons-detector
  namespace: default
data:
  detector: |-
    {
      "broker_uri": "amqp://rabbitmq.default",
      "zipkin_host": "zipkin.default",
      "zipkin_port": 9411,
      "models_folder": "/",
      "resize": {
        "width": 432,
        "height": 368
      },
      "model": "MOBILENET_THIN",
      "resize_out_ratio": 4.0,
      "gpu_mem_allow_growth": true,
      "per_process_gpu_memory_fraction": 0.25
    }

---

apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: "is-skeletons-detector"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: detector
    spec:
      nodeSelector:
        kubernetes.io/hostname: cheetara
      containers:
      - name: "0"
        image: viros/is-skeletons-detector:1.1
        command: ["python"]
        args: ["stream.py", "/opt/options.json"]
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: "1"
            memory: 2048Mi
            nvidia.com/gpu: 1
        volumeMounts:
          - name: options
            mountPath: /opt
      - name: "1"
        image: viros/is-skeletons-detector:1.1
        command: ["python"]
        args: ["stream.py", "/opt/options.json"]
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: "1"
            memory: 2048Mi
        volumeMounts:
          - name: options
            mountPath: /opt
      - name: "2"
        image: viros/is-skeletons-detector:1.1
        command: ["python"]
        args: ["stream.py", "/opt/options.json"]
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: "1"
            memory: 2048Mi
        volumeMounts:
          - name: options
            mountPath: /opt
      - name: "3"
        image: viros/is-skeletons-detector:1.1
        command: ["python"]
        args: ["stream.py", "/opt/options.json"]
        imagePullPolicy: Always
        resources:
          limits: 
            cpu: "1"
            memory: 2048Mi
        volumeMounts:
          - name: options
            mountPath: /opt
      volumes:
      - name: options
        configMap:
          name: skeletons-detector
          items:
          - key: detector
            path: options.json
